if-shell "tmux has-session -t inspection 2>/dev/null" "run-shell 'tmux kill-session -t inspection'"

new-session -d -s inspection -n main -c /inspection_ws "bash -ic 'sr && ros2 launch inspection_planner voxel_grid_simple.launch.py team:=kReal robot:=husky'"
split-window -h -t inspection:main.1 -c /inspection_ws "bash -ic 'sr && ros2 launch inspection_planner planner.launch.py team:=kReal robot:=husky'"
split-window -v -t inspection:main.2 -c /inspection_ws "bash -ic 'sr && rviz2 -d src/FLIP-First-Look-Inspection-Planner/utilities/config/viz.rviz'"
split-window -v -t inspection:main.3 -c /inspection_ws "bash"
split-window -v -t inspection:main.4 -c /inspection_ws "bash"

select-layout -t inspection:main tiled
select-pane -t inspection:main.0

# Launch with tmux start-server \; source-file src/FLIP-First-Look-Inspection-Planner/utilities/config/inspection.tmux.conf \; attach-session -t inspection