planner_node:
  ros__parameters:
    world_frame: world
    sensor_frame: realsense
    base_link_frame: pelican/base_link
    platform_modality: 1
    run_mode: 1
    sensor_modality: 0
    max_sensor_range: 10.0
    min_sensor_range: 0.5
    sensor_range:
    - 0.5
    - 10.0
    sensor_rotation:
    - 0.0
    - 0.0
    - -1.57
    fov:
    - 69.4
    - 45.0
    aspect_ratio: 1.33
    rotation:
    - 0.0
    - 0.0
    - 0.0
    translation:
    - 0.0
    - 0.0
    - 0.0
    max_std_deviation: 1.0
    adaptive_factor: 0.0
    cmd_pos_upd: 0.35
    cmd_yaw_upd: 0.2
    min_pts_conf: 5
    interpolation_alpha: 0.3
    confidence_horizon: 5
    inspection_distance: 5
    photogrammetric_params:
    - 0.6
    - 0.01
    prediction_horizon: 5
    FretD_confidence: 0.5
    inspection_height: 1.0
    odom_topic: ground_truth/odometry
    pcl_topic: filtered_pointcloud
    imu_topic: imu/data
    sbl_topic: sbl/data
    takeoff_topic: start
    land_topic: land
    stop_topic: stop
    reference_pose: command/pose
    inspection_performance: inspection_planner/results/inspection_performance
    tracked_path: inspection_planner/results/tracked_path
    predicted_path: inspection_planner/results/predicted_path
    maintained_distance: inspection_planner/results/maintained_distance
    cropped_points: inspection_planner/results/cropped_points
